version: '3'
volumes:
  pg_data:
  static:
services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  trialapp:
    build: ./TrialApp/
    env_file: .env
    volumes:
      - static:/trialapp_static
    depends_on:
      - db
  gateway:
    build: ./gateway/
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
