version: '3.8'

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: trumphack/trialapp
    env_file: .env
    volumes:
      - static_volume:/trialapp_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: trumphack/trialapp-frontend
    depends_on:
      - backend

  gateway:
    image: trumphack/trialappgateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - media:/media
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend

volumes:
  pg_data_production:
  static_volume:
  media:
