version: "3.8"

services:
  db:
    image: postgres:15
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: trumphack/trialapp-backend:latest
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: always

  frontend:
    image: trumphack/trialapp-frontend:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

  gateway:
    image: trumphack/trialapp-gateway:latest
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  pg_data:
