version: '3'
volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  trialapp:
    image: trumphack/trialapp
    env_file: .env
    volumes:
      - static_volume:/trialapp_static
  gateway:
    image: trumphack/trialappgateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80
